name: Build
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - 'src/**'
      - Dockerfile
      - package.json
      - package-lock.json
      - tsconfig.json
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - Dockerfile
      - package.json
      - package-lock.json
      - tsconfig.json

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build -t slidev-worker:latest .
