name: Lint
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
    paths:
      - 'backend/src/**'
      - backend/Dockerfile
      - backend/package.json
      - backend/package-lock.json
      - backend/tsconfig.json
  push:
    branches:
      - main
    paths:
      - 'backend/src/**'
      - backend/Dockerfile
      - backend/package.json
      - backend/package-lock.json
      - backend/tsconfig.json


jobs:
  lint:
    name: Lint (Oxlint)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cd backend/
      - uses: oxc-project/oxlint-action@v2.0.1
        with:
          config: .oxlintrc.json
